!function(e){var t={};function n(o){if(t[o])return t[o].exports;var r=t[o]={i:o,l:!1,exports:{}};return e[o].call(r.exports,r,r.exports,n),r.l=!0,r.exports}n.m=e,n.c=t,n.d=function(e,t,o){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:o})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var r in e)n.d(o,r,function(t){return e[t]}.bind(null,r));return o},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./src/js/pages.js")}({"./src/js/modules/menu.js":
/*!********************************!*\
  !*** ./src/js/modules/menu.js ***!
  \********************************/
/*! exports provided: default */function(e,t,n){"use strict";n.r(t),t.default=function(e,t,n,o,r){document.querySelectorAll(e).forEach(e=>{e.onmousemove=t=>{e.onclick=()=>{let n=document.createElement("div");n.classList.add("click"),n.style.left=t.clientX-e.offsetLeft-705+"px",n.style.top=t.clientY-e.offsetTop+"px",e.appendChild(n),setTimeout(()=>{n.remove()},1e3)}}});const s=document.querySelector(".menu__logo"),c=document.querySelector(".menu__wrapper");window.addEventListener("scroll",()=>{scrollY>=200?(s.classList.remove("bigLogo"),c.classList.remove("flex-end")):(s.classList.add("bigLogo"),c.classList.add("flex-end"))})}},"./src/js/modules/pageUp.js":
/*!**********************************!*\
  !*** ./src/js/modules/pageUp.js ***!
  \**********************************/
/*! exports provided: default */function(e,t,n){"use strict";n.r(t);var o=n(/*! ../services/constFunctions */"./src/js/services/constFunctions.js");t.default=function(e){const t=document.querySelector(e);window.addEventListener("scroll",()=>{scrollY>=800?Object(o.fadeIn)(t,1e3,.7):Object(o.fadeOut)(t,1e3,0)})}},"./src/js/pages.js":
/*!*************************!*\
  !*** ./src/js/pages.js ***!
  \*************************/
/*! no exports provided */function(e,t,n){"use strict";n.r(t);var o=n(/*! ./modules/menu */"./src/js/modules/menu.js"),r=n(/*! ./modules/pageUp */"./src/js/modules/pageUp.js"),s=n(/*! ./services/constFunctions */"./src/js/services/constFunctions.js");window.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".preload");window.addEventListener("load",(function(){document.querySelector("body").removeAttribute("style"),e.remove()})),Object(o.default)(".menu__item_link",".menu__logo","bigLogo",".menu__wrapper","flex-end"),Object(r.default)(".pageup"),Object(s.videoHeight)(".curs__video")})},"./src/js/services/constFunctions.js":
/*!*******************************************!*\
  !*** ./src/js/services/constFunctions.js ***!
  \*******************************************/
/*! exports provided: fadeIn, fadeOut, videoHeight */function(e,t,n){"use strict";n.r(t),n.d(t,"fadeIn",(function(){return o})),n.d(t,"fadeOut",(function(){return r})),n.d(t,"videoHeight",(function(){return s}));const o=(e,t,n,o,r)=>{e.style.opacity=n||1,e.style.visibility=o||"visible",e.style.display=r||"block",e.style.transition=`all ${t}ms`},r=(e,t,n,o)=>{e.style.opacity=n||0,e.style.visibility=o||"hidden",e.style.transition=`all ${t}ms`};function s(e){const t=document.querySelector(e);if(t){const e=t.querySelector("iframe"),n=window.getComputedStyle(e,null).getPropertyValue("width"),o=Math.round(.5625*+n.slice(0,-2));t.style.height=o+"px"}}}});
//# sourceMappingURL=pages.js.map